services:
  postgres:
    image: postgres:16-alpine
    container_name: core-bank-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: core-bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-k8084164}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d core-bank"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core-bank-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/core-bank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-k8084164}
      JWT_SECRET: ${JWT_SECRET:-RoiBVeTm42Ly8ckrEYcSub658z4AWHYU}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
