@token = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W10sInVzZXJJZCI6MiwiZW1haWwiOiJrYW1wYXJzZW5AeWFob28uY29tIiwic3ViIjoia2FtcGFyc2VuIiwiaWF0IjoxNzkwNTYxODUyLCJleHAiOjE3OTA2NDgyNTJ9.tFx4syuJVUXDs7UXq2xOr4dv4IoJmCePs3pn9P4h_eU
@accountId = 1

### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Get Users
GET localhost:8080/api/auth/users


### Register new user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "kamparsen",
  "password": "Kk8084164",
  "email": "kamparsen@yahoo.com",
  "fullName": "Kam Parsen"
}

### Register new user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "Rustin2",
  "password": "Kk8084163",
  "email": "rustin2@yahoo.com",
  "fullName": "Rustin2 Parsen"
}

### Register new user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "john_doe",
  "password": "Password123",
  "email": "johmdo@yahoo.com",
  "fullName": "John Doe"
}

### Login user
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "john_doe",
  "password": "Password123"
}

### Login user
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "kamparsen",
  "password": "Kk8084164"
}

### Get users using JWT token
GET http://localhost:8080/api/auth/users
Authorization: Bearer <paste-your-token-here>

### Get users using JWT token
GET http://localhost:8080/api/auth/users2
Authorization: Bearer {{token}}

### Create account
POST http://localhost:8080/api/auth/accounts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user": {
    "id": 1
  },
  "accountNumber": "1000000001",
  "accountType": "SAVINGS",
  "balance": 250.00

}



### Deposit into account
POST http://localhost:8080/api/auth/accounts/{{accountId}}/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount": 50.00,
  "description": "Test deposit"
}

### Get current authenticated user info
GET http://localhost:8080/api/auth/me
Authorization: Bearer {{token}}

